#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Stephen J

# Short bio or description (displayed in the header)
description: Web Developer and tech lover

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars3.githubusercontent.com/u/26724777?s=460&v=4

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook: skipishere
  flickr:
  github: 
  instagram:
  linkedin: stephencharlesjones
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: skuldo
  stackoverflow: users/839992/skuld # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: StephenJonesIsHere # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: stephenj

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-33077218-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://blog.stephenj.co.uk

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

webrick:
  headers:
    Content-Security-Policy-Report-Only: default-src 'self'; img-src 'self' https://avatars3.githubusercontent.com; frame-src https://disqus.com/; script-src 'self' https://www.google-analytics.com https://www.googletagmanager.com https://disqus.com https://c.disquscdn.com https://{{ site.disqus }}.disqus.com report-uri https://7759e86b05daeeced19f70967b7ed994.report-uri.com/r/d/csp/reportOnly

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-cayman